// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;  */

const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Quick Start Guide',
      items: ['quick-start/quick-start-guide'],
    },
    {
      type: 'category',
      label: 'User Guide',
      items: ['user-guide/user-guide'],
    },
    {
      type: 'category',
      label: 'Census Galaxy',
      items: [
        'census-galaxy/overview',
        'census-galaxy/geographies',
        'census-galaxy/data-sources',
        'census-galaxy/metrics',
      ],
    },
    {
      type: 'category',
      label: 'Data',
      items: [
        {
          type: 'category',
          label: 'Geographies',
          items: ['data/geographies/block-groups'],
        },
        {
          type: 'category',
          label: 'Metrics',
          items: ['data/metrics/base-demographics'],
        },
      ],
    },
  ],
};

export default sidebars;

